mode: immediate
branchName: issues/${issue.number}
branches:
  - name: develop

autoLinkIssue: true
autoCloseIssue: true
openPR: true

copyIssueDescriptionToPR: true
copyIssueAssigneeToPR: true
copyIssueLabelsToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
