mode: immediate
branchName: ${issue.number}
branches:
  - label: "*"
    name: develop
    prefix: issues/

autoLinkIssue: true
autoCloseIssue: true
openPR: true

copyIssueDescriptionToPR: true
copyIssueAssigneeToPR: true
copyIssueLabelsToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
