name: Auto create branch from issue

on:
  issues:
    types: [ opened ]
  pull_request:
    types: [ opened, closed ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create new Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
